### PR TITLE
Change license to MIT OR Apache-2.0

### LINKED ISSUE #21: Request for License Conversion to MIT or Apache 2.0
This ticket is to request a change in the current project license to either the MIT License or the Apache License 2.0. There are useful parts for serialization that we would like to copy to our project but license is not compatible with [Burn's project](https://github.com/burn-rs/burn).

### PR DESCRIPTION
**Pull request by antimora**
Fixes #21

### CODE REVIEW

**Comment by antimora** [comment]
Dear @twistedfall, @samoylovfp, @hdhoang,

Kindly requesting to re-license your work in serde-rustsqlite under MIT or Apache-2.0, so that the users of [Burn project ](https://github.com/burn-rs/burn) can distribute binaries. Please see #21 for more details.

**Comment by samoylovfp** [comment]
Permission is hereby granted by me (samoylovfp) to re-license the changes I have made to the source code of this project (serde_rusqlite). My contributions can now be licensed under MIT AND/OR Apache 2 licenses.

Thank you  for maintaining this project.

**Comment by twistedfall** [comment]
Let's wait for another confirmation and I'll merge this, thanks for making the effort for this PR

**Comment by hdhoang** [comment]
I (hdhoang) dedicate my contributions in this project to the public domain, and hereby disown any and all copyright on them.

Wish you all lucks.

**Comment by twistedfall** [comment]
I have released version 0.34.0 with that change (and rusqlite bump)

**Comment by antimora** [comment]
@twistedfall Than you very much!

**Pull request merged**
